org: carlosaguirre5
app: link
service: link-dev

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

functions:
  hello:
    handler: handler.get_inventario
    events:
    - http:
        path: inventario
        method: get
plugins:
  - serverless-offline
  - serverless-python-requirements